// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ADMReestructuracion.Auth.DataAccess.Models;
using ADMReestructuracion.Auth.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ADMReestructuracion.Auth.DataAccess.Repositories.Configurations
{
    public partial class GenUsuarioConfiguration : IEntityTypeConfiguration<GenUsuario>
    {
        public void Configure(EntityTypeBuilder<GenUsuario> entity)
        {
            entity.HasKey(e => e.IdUsuario).HasName("_copy_17");

            entity.Property(e => e.Ad).HasColumnName("AD");
            entity.Property(e => e.Apellidos)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Clave)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.CodigoUsuario)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Correo)
            .HasMaxLength(60)
            .IsUnicode(false);
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");
            entity.Property(e => e.Identificacion)
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.Nombres)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Qr).HasColumnName("QR");
            entity.Property(e => e.RutaQr)
            .HasMaxLength(255)
            .IsUnicode(false)
            .HasColumnName("RutaQR");
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioRegistro)
            .HasMaxLength(100)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GenUsuario> entity);
    }
}
