// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADMReestructuracion.Auth.DataAccess.Models;

public partial class GenUsuario
{
    public int IdUsuario { get; set; }

    public int IdTipoIdentificacion { get; set; }

    public int? IdTipoSangre { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Correo { get; set; }

    public string CodigoUsuario { get; set; }

    public string Clave { get; set; }

    public bool? Ad { get; set; }

    public bool? Qr { get; set; }

    public string RutaQr { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public string Identificacion { get; set; }
}